-- 1. Tạo bảng users (nếu chưa có)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_uid UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    role TEXT DEFAULT 'customer',
    username TEXT,
    email TEXT,
    full_name TEXT,
    phone_number TEXT,
    avatar_url TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Bật RLS cho bảng users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 2. Tạo policy: Người dùng chỉ được SELECT thông tin của chính mình
CREATE POLICY "Users can view own profile" 
ON public.users 
FOR SELECT 
USING (auth.uid() = auth_uid);

-- 3. Tạo policy: Người dùng chỉ được UPDATE thông tin của chính mình
CREATE POLICY "Users can update own profile" 
ON public.users 
FOR UPDATE 
USING (auth.uid() = auth_uid);

-- 4. Tạo hàm Trigger: Tự động copy user từ auth.users sang public.users khi đăng ký
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (auth_uid, email, username)
  VALUES (new.id, new.email, split_part(new.email, '@', 1));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Gắn Trigger vào bảng auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 6. Dành cho các user đã đăng ký trước đó (chạy 1 lần để đồng bộ dữ liệu cũ)
INSERT INTO public.users (auth_uid, email, username)
SELECT id, email, split_part(email, '@', 1)
FROM auth.users
WHERE id NOT IN (SELECT auth_uid FROM public.users WHERE auth_uid IS NOT NULL);
